/**
 * GENERATED by scripts/build-tokens.mjs from design/tokens.json — do not edit.
 * Change the palette there and run `node scripts/build-tokens.mjs`.
 *
 * The delivery page is rendered by the API as one HTML string and cannot load
 * the app's stylesheet, so its colours arrive as constants instead.
 */
export const DELIVERY_PALETTE = {
  light: {
    paper: '#FBF7F2',
    ink: '#201C19',
    muted: '#6F5C52',
    line: '#DED3CA',
    accent: '#A85D35',
    accentInk: '#FFFFFF',
  },
  dark: {
    paper: '#171411',
    ink: '#F2EDE8',
    muted: '#A89488',
    line: '#302A26',
    accent: '#D18A5A',
    accentInk: '#171411',
  },
  panel: '#211D1A',
  panelInk: '#FFFFFF',
  panelMuted: 'rgba(255,255,255,0.74)',
  panelAccent: '#E0A97C',
} as const;
