/**
 * GENERATED by scripts/build-tokens.mjs from design/tokens.json — do not edit.
 * Change the palette there and run `node scripts/build-tokens.mjs`.
 */

export interface Palette {
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  popover: string;
  popoverForeground: string;
  primary: string;
  primaryForeground: string;
  action: string;
  actionForeground: string;
  secondary: string;
  secondaryForeground: string;
  muted: string;
  mutedForeground: string;
  accent: string;
  accentForeground: string;
  destructive: string;
  destructiveForeground: string;
  success: string;
  warning: string;
  info: string;
  border: string;
  input: string;
  ring: string;
}

export const PALETTES: { light: Palette; dark: Palette } = {
  light: {
    background: '#FFF8F4',
    foreground: '#1E1B18',
    card: '#FFFFFF',
    cardForeground: '#1E1B18',
    popover: '#FFFFFF',
    popoverForeground: '#1E1B18',
    primary: '#A85D35',
    primaryForeground: '#FFFFFF',
    action: '#A85D35',
    actionForeground: '#FFFFFF',
    secondary: '#FAF2EC',
    secondaryForeground: '#54433C',
    muted: '#F5EEE8',
    mutedForeground: '#7B675D',
    accent: '#C17745',
    accentForeground: '#FFFFFF',
    destructive: '#B44632',
    destructiveForeground: '#FFFFFF',
    success: '#4A6B3A',
    warning: '#9A5424',
    info: '#4A6A88',
    border: '#D9C2B7',
    input: '#D9C2B7',
    ring: '#B66A40',
  },
  dark: {
    background: '#161311',
    foreground: '#F2EDE8',
    card: '#1E1B18',
    cardForeground: '#F2EDE8',
    popover: '#1E1B18',
    popoverForeground: '#F2EDE8',
    primary: '#D18A5A',
    primaryForeground: '#161311',
    action: '#A85D35',
    actionForeground: '#FFFFFF',
    secondary: '#26221F',
    secondaryForeground: '#BCADA3',
    muted: '#2A2522',
    mutedForeground: '#A08E84',
    accent: '#B66A40',
    accentForeground: '#FFFFFF',
    destructive: '#C8503C',
    destructiveForeground: '#FFFFFF',
    success: '#7DA55C',
    warning: '#D9986A',
    info: '#6D90B1',
    border: '#362F2B',
    input: '#362F2B',
    ring: '#C17745',
  },
};

/** Chart series past the first two, which lead with primary and accent. */
export const CHART_TAIL = ['#8B5E3C', '#6B8E4E', '#5B7B9A'] as const;

/** Points, as NativeWind's --radius wants it. */
export const RADIUS = 14;
