-- A tiny inline preview, painted before anything is fetched.
--
-- The grid already reserves the right box — `aspectRatio` comes from
-- width_px/height_px, so nothing reflows — but until a thumbnail arrives that
-- box is flat colour. On a phone on Philippine mobile data that is a screen of
-- grey rectangles for a beat, which is the difference between a gallery that
-- feels instant and one that feels like it is loading.
--
-- A ~300 byte `data:image/webp;base64,…` of a twenty-pixel version of the
-- image. It rides in the album listing that already enumerates the files, so
-- it costs no extra request: a two-hundred photograph gallery paints
-- completely before a single thumbnail is fetched.
--
-- Text rather than bytea: it is consumed as a string by three clients and
-- never manipulated, so storing it decoded would mean base64-encoding it on
-- every read for nothing.
alter table user_files
  add column if not exists blur_data_url text;

-- No requeue, for the same reason as 061.
--
-- A photograph's preview is made on the confirm path by ThumbnailsService,
-- from the decoded original. A film's is made by the media worker, from the
-- poster frame it extracts. Filling them in for an existing library means
-- reading every photograph back out of B2, which is an operator decision, not
-- something a migration does on boot. The backfill from 061 does it, inside
-- the API container:
--
--   docker exec virgo-api node scripts/backfill-thumbnails.mjs --dry-run
--   docker exec virgo-api node scripts/backfill-thumbnails.mjs
--
-- A photograph's preview comes from the same read that makes any display
-- copies or thumbnail it still lacks. A film's comes from its poster, a small
-- WebP rather than the film; a film with no poster has nothing to make one
-- from and is skipped.
--
-- Until it runs, older media keeps showing the flat box it shows today.
-- Nothing breaks while it is pending; the clients treat null as "no preview".
