#!/usr/bin/env node
/**
 * Writes design/tokens.json into every client that draws with it.
 *
 *   node scripts/build-tokens.mjs           write the generated files
 *   node scripts/build-tokens.mjs --check   fail if any of them differ
 *
 * Before this, the palette was typed out three times. The web and console
 * stylesheets each said "Same values as mobile/theme.ts" above values that
 * were not the same — a primary two shades lighter, a muted grey that failed
 * contrast on the web and passed on the phone — and nothing could notice.
 * Now the copies are outputs, and `--check` (also run by
 * check-client-sync.mjs) fails the moment one is edited by hand.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(root, 'design', 'tokens.json'), 'utf8'));
const CHECK = process.argv.includes('--check');

const BANNER =
  'GENERATED by scripts/build-tokens.mjs from design/tokens.json — do not edit.\n' +
  'Change the palette there and run `node scripts/build-tokens.mjs`.';

// ── The phone app ───────────────────────────────────────────────────────────

/** The phone's names for each token. `accent` there is the brand accent. */
const MOBILE_KEYS = [
  ['background', 'background'],
  ['foreground', 'foreground'],
  ['card', 'card'],
  ['cardForeground', 'cardForeground'],
  ['popover', 'popover'],
  ['popoverForeground', 'popoverForeground'],
  ['primary', 'primary'],
  ['primaryForeground', 'primaryForeground'],
  ['action', 'action'],
  ['actionForeground', 'actionForeground'],
  ['secondary', 'secondary'],
  ['secondaryForeground', 'secondaryForeground'],
  ['muted', 'muted'],
  ['mutedForeground', 'mutedForeground'],
  ['accent', 'brandAccent'],
  ['accentForeground', 'brandAccentForeground'],
  ['destructive', 'destructive'],
  ['destructiveForeground', 'destructiveForeground'],
  ['success', 'success'],
  ['warning', 'warning'],
  ['info', 'info'],
  ['border', 'border'],
  ['input', 'input'],
  ['ring', 'ring'],
];

function mobileFile() {
  const palette = (mode) =>
    MOBILE_KEYS.map(([name, token]) => `    ${name}: '${tokens[mode][token]}',`).join('\n');
  return `/**
 * ${BANNER.replace(/\n/g, '\n * ')}
 */

export interface Palette {
${MOBILE_KEYS.map(([name]) => `  ${name}: string;`).join('\n')}
}

export const PALETTES: { light: Palette; dark: Palette } = {
  light: {
${palette('light')}
  },
  dark: {
${palette('dark')}
  },
};

/** Chart series past the first two, which lead with primary and accent. */
export const CHART_TAIL = ['${tokens.light.chart3}', '${tokens.light.chart4}', '${tokens.light.chart5}'] as const;

/** Points, as NativeWind's --radius wants it. */
export const RADIUS = ${tokens.radius.mobile};
`;
}

// ── The web app and the console ─────────────────────────────────────────────

/** shadcn's names, where the web's --accent is the hover surface. */
function cssBlock(mode) {
  const t = tokens[mode];
  const vars = [
    ['background', t.background],
    ['foreground', t.foreground],
    ['card', t.card],
    ['card-foreground', t.cardForeground],
    ['popover', t.popover],
    ['popover-foreground', t.popoverForeground],
    ['primary', t.primary],
    ['primary-foreground', t.primaryForeground],
    ['action', t.action],
    ['action-foreground', t.actionForeground],
    ['secondary', t.secondary],
    ['secondary-foreground', t.secondaryForeground],
    ['muted', t.muted],
    ['muted-foreground', t.mutedForeground],
    ['accent', t.hover],
    ['accent-foreground', t.hoverForeground],
    ['brand-accent', t.brandAccent],
    ['destructive', t.destructive],
    ['destructive-foreground', t.destructiveForeground],
    ['success', t.success],
    ['warning', t.warning],
    ['info', t.info],
    ['border', t.border],
    ['input', t.input],
    ['ring', t.ring],
    ['chart-1', t.primary],
    ['chart-2', t.brandAccent],
    ['chart-3', t.chart3],
    ['chart-4', t.chart4],
    ['chart-5', t.chart5],
    ['sidebar', t.sidebar],
    ['sidebar-foreground', t.sidebarForeground],
    ['sidebar-primary', t.primary],
    ['sidebar-primary-foreground', t.primaryForeground],
    ['sidebar-accent', t.sidebarAccent],
    ['sidebar-accent-foreground', t.sidebarAccentForeground],
    ['sidebar-border', t.sidebarBorder],
    ['sidebar-ring', t.ring],
  ];
  if (mode === 'light') vars.push(['radius', tokens.radius.web]);
  return vars.map(([name, value]) => `  --${name}: ${String(value).toLowerCase()};`).join('\n');
}

function cssFile() {
  return `/*
 * ${BANNER.replace(/\n/g, '\n * ')}
 */

:root {
${cssBlock('light')}
}

.dark {
${cssBlock('dark')}
}
`;
}

// ── The client delivery page ────────────────────────────────────────────────

function deliveryFile() {
  const d = tokens.delivery;
  const entries = (obj) =>
    Object.entries(obj)
      .filter(([key]) => !key.startsWith('$'))
      .map(([key, value]) => `    ${key}: '${value}',`)
      .join('\n');
  return `/**
 * ${BANNER.replace(/\n/g, '\n * ')}
 *
 * The delivery page is rendered by the API as one HTML string and cannot load
 * the app's stylesheet, so its colours arrive as constants instead.
 */
export const DELIVERY_PALETTE = {
  light: {
${entries(d.light)}
  },
  dark: {
${entries(d.dark)}
  },
  panel: '${d.panel}',
  panelInk: '${d.panelInk}',
  panelMuted: '${d.panelMuted}',
  panelAccent: '${d.panelAccent}',
} as const;
`;
}

// ── Write or compare ────────────────────────────────────────────────────────

const outputs = [
  ['mobile/theme.tokens.ts', mobileFile()],
  ['web/src/app/tokens.css', cssFile()],
  ['dashboard/src/app/tokens.css', cssFile()],
  ['api/src/albums/share/client-palette.ts', deliveryFile()],
];

const stale = [];
for (const [path, content] of outputs) {
  const full = join(root, path);
  if (CHECK) {
    let current = null;
    try {
      current = readFileSync(full, 'utf8').replace(/\r\n/g, '\n');
    } catch {
      // Missing counts as stale.
    }
    if (current !== content) stale.push(path);
  } else {
    writeFileSync(full, content);
    console.log(`wrote ${path}`);
  }
}

if (CHECK) {
  if (stale.length) {
    console.log('Generated palette files are out of date with design/tokens.json:');
    for (const path of stale) console.log(`  ${path}`);
    console.log('\nRun `node scripts/build-tokens.mjs` — and edit tokens.json, never these.');
    process.exit(1);
  }
  console.log(`Palette: ${outputs.length} generated file(s) match design/tokens.json.`);
}
